Description: "Basic NotebookInstance test update to a different instance type"
Parameters:
  SageMakerRepo:
    Description: github clone url
    Type: String
    Default: "git@github.com:ICFI/dragon.git"
Resources:
  BasicNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.t2.large"
      RoleArn: !GetAtt ExecutionRole.Arn
      LifecycleConfigName: !GetAtt BasicNotebookInstanceLifecycleConfig.NotebookInstanceLifecycleConfigName
  BasicNotebookInstanceLifecycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      OnStart:
        - Content:
            Fn::Base64: !Sub |
              #!/bin/bash -x
              sudo -u ec2-user -i <<'EOF'

              mkdir -p ~/.ssh

              aws secretsmanager get-secret-value --secret-id GitDeployPrivKey | jq .SecretString -r | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba'  > ~/.ssh/id_rsa
              aws secretsmanager get-secret-value --secret-id GitDeployPubKey | jq .SecretString -r | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba'  > ~/.ssh/id_rsa.pub
              chmod 600 ~/.ssh/id_rsa*

              cd SageMaker

              git clone ${SageMakerRepo}

              cat > ~/.ssh/config << HOSTCHECKING
              Host *
                 StrictHostKeyChecking no
              HOSTCHECKING

  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"
Outputs:
  BasicNotebookInstanceId:
    Value: !Ref BasicNotebookInstance
